### ISSUE TITLE
not work with interactive chat

### ISSUE THREAD

**Issue by LowScarlet** [AlessioDP/Parties#217]
![image](https://user-images.githubusercontent.com/64282946/208302996-28c39084-75cd-465f-bf9e-e5163c248aa8.png)

**Comment by AlessioDP** [comment]
I tested it and it works with both /p command and party chat toggle.
You may need to change the event priorities of InteractiveChat into something lower than the default one:
```yaml
EventPriorities:
    # Defaults to HIGH
    Commands: HIGH
    # Defaults to HIGH
    Chat: LOW
    # Defaults to HIGH
    Preview: HIGH
```
